---
Standards:
  -
    Title: About Problem-Solving Exercises
    Description: About PSEs
    UID: de695bcc40c90003ead81729ffd35342
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 71d8142849851c1999d31842cddb2aa4
        Path: /about-pses/about-pses.md
      -
        Type: Lesson
        UID: TNrFPV
        Path: /about-pses/example-pse.md
  -
    Title: PSE 01
    Description: Calculator
    UID: 0a601cc26210e6eed0bd55f8a843ca8f
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 10ddabe050188bf867ffe5c5ccb689ae
        Path: /01/calculator.md
  -
    Title: PSE 02
    Description: Data Transformation
    UID: 43f37536-7fe3-4a01-8832-9bad151b2d7f
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 5e834674-1c56-48f8-ae3d-ef598f3d79a7
        Path: /02/data-transformation.md
  -
    Title: PSE 03
    Description: Hamming
    UID: 1d305fd4-0793-406e-882d-6f6ab1d6c0e7
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 43e4b99a-7df0-4147-8bea-2f08465d0c47
        Path: /03/hamming.md
  -      
    Title: PSE 04
    Description: Palindrome
    UID: f7460e9e-f0af-43d4-b393-09745c83f772
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Checkpoint
        UID: 0a9625c9-fb2b-4dbf-96f8-e1fd03a60acb
        Path: /04/palindrome.checkpoint.md        
  -
    Title: PSE 05
    Description: Pairs with Given Sum
    UID: ab5d6542-f49a-419a-814e-03872bb60c84
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Checkpoint
        UID: cebb89a0-61f0-4bc0-a889-6654045c839c
        Path: /05/pairs-with-given-sum.checkpoint.md
  -
    Title: PSE 06
    Description: Merging Sorted Lists
    UID: 3253d4dd-bf5c-484b-8481-2d85f3844213
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Checkpoint
        UID: f937f38d-b86d-4607-8203-b579e1f1689e
        Path: /06/merging-sorted-lists.checkpoint.md      
  -
    Title: PSE 07
    Description: Reshape a Matrix
    UID: d3ddc88a-afbe-43c7-b1f1-8e7b98cecdc3
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Checkpoint          
        UID: 6cfc6d12-7850-4236-be85-64d8a6259f07
        Path: /07/reshape-a-matrix.checkpoint.md
  -
    Title: PSE 08
    Description: Tic Tac Toe
    UID: 5f521cbc-b5bd-4f63-9e8f-66da369a2100
    SuccessCriteria:
      - success criteria
    ContentFiles:    
      -
        Type: Checkpoint
        UID: 7bee6de0-766a-49b2-b5d4-5d142cab76d7
        Path: /10/tictactoe.checkpoint.md
  -
    Title: PSE 09
    Description: Kth Missing Positive Number
    UID: 104de1dc-9c42-4da8-b94f-802c36bbbd6c
    SuccessCriteria:
      - success criteria
    ContentFiles:    
      -
        Type: Checkpoint
        UID: 2b22f6b1-ca0c-4dc9-8913-b62ab2698fbe
        Path: /08/kth-missing-positive-number.checkpoint.md
  -
    Title: PSE 10 (skip)
    Description: Knapsack
    UID: 893115f8-70b1-419b-9326-9b4fb2c60f39
    SuccessCriteria:
      - success criteria
    ContentFiles:    
      -
        Type: Checkpoint
        UID: 80c3108d-1015-4ecc-a7ae-226ff4c76eed
        Path: /09/knapsack.checkpoint.md
      