---
Standards:
  -
    Title: About Problem-Solving Exercises
    Description: About PSEs
    UID: de695bcc40c90003ead81729ffd35342
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: aed96068-4923-4103-a85e-0dec07716345
        Path: /about-pses/example-pse.instructor.md
      -
        Type: Lesson
        UID: 71d8142849851c1999d31842cddb2aa4
        Path: /about-pses/about-pses.md
      -
        Type: Lesson
        UID: aef97120-8ddc-4bb2-ad0e-28638c523bb1
        Path: /about-pses/example-pse.md
  -
    Title: PSE 01
    Description: Highest Rated
    UID: 0a601cc26210e6eed0bd55f8a843ca8f
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: e69885f5
        Path: /01/highest-rated.md
      -
        Type: Instructor
        UID: c31f34cf
        Path: /01/implement-highest-rated.instructor.md
      -
        Type: Checkpoint
        UID: ea70e2d3
        Path: /01/implement-highest-rated.checkpoint.md
  -
    Title: PSE 02
    Description: Adagrams
    UID: e2a3cbde-4cac-4b47-abb3-87564462ab2a
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 87250cbe
        Path: /02/adagrams.md
      -
        Type: Instructor
        UID: 43859c74
        Path: /02/implement-adagrams.instructor.md
      -
        Type: Checkpoint
        UID: 21c2af2f
        Path: /02/implement-adagrams.checkpoint.md
  -
    Title: PSE 03
    Description: Hamming
    UID: ceb82f7e-cdcd-44dd-aa1a-85ea7ba21c56
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: d7aa63a9-1797-4f71-963a-67eadad331c6
        Path: /03/implement-hamming.instructor.md
      -
        Type: Lesson
        UID: 1347008a-8d71-4a06-860b-408d596999e0
        Path: /03/hamming.md
      -
        Type: Checkpoint
        UID: a696f346-07b3-46d4-85fc-da678eb67786
        Path: /03/implement-hamming.checkpoint.md
  -      
    Title: PSE 04
    Description: Palindrome
    UID: f7460e9e-f0af-43d4-b393-09745c83f772
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Checkpoint
        UID: 0a9625c9-fb2b-4dbf-96f8-e1fd03a60acb
        Path: /04/palindrome.checkpoint.md        
  -
    Title: PSE 05
    Description: Pairs with Given Sum
    UID: ab5d6542-f49a-419a-814e-03872bb60c84
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: cebb89a0-61f0-4bc0-a889-6654045c839c
        Path: /05/pairs-with-given-sum.md
      -
        Type: Lesson
        UID: 2b426e2c-dd8a-4b02-8aca-8a1fe9aed6af
        Path: /05/implement-pairs-with-given-sum.instructor.md
      -
        Type: Checkpoint
        UID: 7c6d5b64-150b-4ece-a88c-c06ad0dd1581
        Path: /05/implement-pairs-with-given-sum.checkpoint.md
  -
    Title: PSE 06
    Description: Merging Sorted Lists
    UID: 3253d4dd-bf5c-484b-8481-2d85f3844213
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Checkpoint
        UID: f937f38d-b86d-4607-8203-b579e1f1689e
        Path: /06/merging-sorted-lists.checkpoint.md      
  -
    Title: PSE 07
    Description: Reshape a Matrix
    UID: d3ddc88a-afbe-43c7-b1f1-8e7b98cecdc3
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Checkpoint          
        UID: 6cfc6d12-7850-4236-be85-64d8a6259f07
        Path: /07/reshape-a-matrix.checkpoint.md
  -
    Title: PSE 08
    Description: Kth Missing Positive Number
    UID: 104de1dc-9c42-4da8-b94f-802c36bbbd6c
    SuccessCriteria:
      - success criteria
    ContentFiles:    
      -
        Type: Checkpoint
        UID: 2b22f6b1-ca0c-4dc9-8913-b62ab2698fbe
        Path: /08/kth-missing-positive-number.checkpoint.md
  -
    Title: PSE 09
    Description: "Best Time to Buy/Sell Stock"
    UID: 893115f8-70b1-419b-9326-9b4fb2c60f39
    SuccessCriteria:
      - success criteria
    ContentFiles:    
      -
        Type: Checkpoint
        UID: 80c3108d-1015-4ecc-a7ae-226ff4c76eed
        Path: /09/stock.checkpoint.md
  -
    Title: PSE 10
    Description: Tic Tac Toe
    UID: 5f521cbc-b5bd-4f63-9e8f-66da369a2100
    SuccessCriteria:
      - success criteria
    ContentFiles:    
      -
        Type: Checkpoint
        UID: 7bee6de0-766a-49b2-b5d4-5d142cab76d7
        Path: /10/tictactoe.checkpoint.md
      