---
Standards:
  -
    Title: About Problem-Solving Exercises
    Description: "Required: About PSEs"
    UID: de695bcc40c90003ead81729ffd35342
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: aed96068-4923-4103-a85e-0dec07716345
        Path: /about-pses/example-pse.instructor.md
      -
        Type: Lesson
        UID: 71d8142849851c1999d31842cddb2aa4
        Path: /about-pses/about-pses.md
      -
        Type: Lesson
        UID: aef97120-8ddc-4bb2-ad0e-28638c523bb1
        Path: /about-pses/example-pse.md
  -
    Title: PSE 01
    Description: Hamming
    UID: ceb82f7e-cdcd-44dd-aa1a-85ea7ba21c56
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: d7aa63a9-1797-4f71-963a-67eadad331c6
        Path: /01/implement-hamming.instructor.md
      -
        Type: Lesson
        UID: 1347008a-8d71-4a06-860b-408d596999e0
        Path: /01/hamming.md
      -
        Type: Checkpoint
        UID: a696f346-07b3-46d4-85fc-da678eb67786
        Path: /01/implement-hamming.checkpoint.md
  -      
    Title: PSE 02
    Description: Palindrome
    UID: f7460e9e-f0af-43d4-b393-09745c83f772
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: e3c48f85-3196-4a81-ab3a-ea5805c74c16
        Path: /02/implement-palindrome.instructor.md 
      -
        Type: Lesson
        UID: 1b14dee4-2b73-4c8c-8c75-5297a328b23f
        Path: /02/palindrome.md 
      -
        Type: Checkpoint
        UID: 0a9625c9-fb2b-4dbf-96f8-e1fd03a60acb
        Path: /02/implement-palindrome.checkpoint.md        
  -
    Title: PSE 03
    Description: Pairs with Given Sum
    UID: ab5d6542-f49a-419a-814e-03872bb60c84
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: 2b426e2c-dd8a-4b02-8aca-8a1fe9aed6af
        Path: /03/implement-pairs-with-given-sum.instructor.md
      -
        Type: Lesson
        UID: cebb89a0-61f0-4bc0-a889-6654045c839c
        Path: /03/pairs-with-given-sum.md
      -
        Type: Checkpoint
        UID: 7c6d5b64-150b-4ece-a88c-c06ad0dd1581
        Path: /03/implement-pairs-with-given-sum.checkpoint.md
  -
    Title: PSE 04
    Description: Merging Sorted Lists
    UID: 3253d4dd-bf5c-484b-8481-2d85f3844213
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: e7c59d8f-b349-4da1-af97-10d0fad11070
        Path: /04/merging-sorted-lists.instructor.md
      -
        Type: Lesson
        UID: f915967b-7b81-46b3-b716-40958c0b88ea
        Path: /04/merging-sorted-lists.md
      -
        Type: Checkpoint
        UID: f937f38d-b86d-4607-8203-b579e1f1689e
        Path: /04/merging-sorted-lists.checkpoint.md   
  -
    Title: PSE 05
    Description: Rotate Linked List
    UID: 2cd65120-ac4d-4e52-a544-94e76a7e8137
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: 32099f7b-a6bf-4120-ae6b-d1f2b477e8a5
        Path: /05/rotate-linked-list.instructor.md
      -
        Type: Lesson
        UID: f3a8ad12-4fa7-4fea-b4c5-7c74cf4a4165
        Path: /05/rotate-linked-list.md
      -
        Type: Checkpoint
        UID: 0b9e2992-f2bb-447f-975c-ee1023c2656c
        Path: /05/rotate-linked-list.checkpoint.md     
  -
    Title: PSE 06
    Description: Reshape a Matrix
    UID: d3ddc88a-afbe-43c7-b1f1-8e7b98cecdc3
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: 70923d5e-8822-4bf5-8c67-36478513edaa
        Path: /06/reshape-a-matrix.instructor.md
      -
        Type: Lesson
        UID: d0f2934f-9f3d-4bd6-b853-fb098b71662c
        Path: /06/reshape-a-matrix.md
      -
        Type: Checkpoint          
        UID: 6cfc6d12-7850-4236-be85-64d8a6259f07
        Path: /06/reshape-a-matrix.checkpoint.md
  -
    Title: PSE 07
    Description: Kth Missing Positive Number
    UID: 104de1dc-9c42-4da8-b94f-802c36bbbd6c
    SuccessCriteria:
      - success criteria
    ContentFiles:    
      -
        Type: Instructor
        UID: 46a263cb-93ca-46aa-9f92-6fe2806feb8c
        Path: /07/kth-missing-positive-number.instructor.md
      -
        Type: Lesson
        UID: 5f9600c6-07b7-4970-b124-73c9486d0238
        Path: /07/kth-missing-positive-number.md
      -
        Type: Checkpoint
        UID: 2b22f6b1-ca0c-4dc9-8913-b62ab2698fbe
        Path: /07/kth-missing-positive-number.checkpoint.md
  -
    Title: PSE 08
    Description: "Best Time to Buy/Sell Stock"
    UID: 893115f8-70b1-419b-9326-9b4fb2c60f39
    SuccessCriteria:
      - success criteria
    ContentFiles:    
      -
        Type: Instructor
        UID: 8832a461-5fbc-4fcf-84a5-3444561b53cc
        Path: /08/stock.instructor.md
      -
        Type: Lesson
        UID: 3c5d7780-b34c-4daa-938b-4bf9f13da0ca
        Path: /08/stock.md
      -
        Type: Checkpoint
        UID: 80c3108d-1015-4ecc-a7ae-226ff4c76eed
        Path: /08/stock.checkpoint.md 
